/*
 * Copyright (C) 2018-2019 Matthias Benkendorf
 */

#ifndef VTM_NET_HTTP_WS_ERROR_H_
#define VTM_NET_HTTP_WS_ERROR_H_

#define VTM_E_WS_RSV_NONZERO            -2500
#define VTM_E_WS_CTRL_MSG_FRAGMENTED    -2501
#define VTM_E_WS_CLIENT_MSG_UNMASKED    -2502
#define VTM_E_WS_SERVER_MSG_MASKED      -2503
#define VTM_E_WS_INVALID_OPCODE         -2504
#define VTM_E_WS_INVALID_PAYLOAD_LEN    -2505
#define VTM_E_WS_BAD_CONTINUE_FRAME     -2506
#define VTM_E_WS_MSG_NOT_CONTINUED      -2507

#endif /* VTM_NET_HTTP_WS_ERROR_H_ */
